import CoreGraphics
import Foundation

public enum PhysicalKeyboardSuppressionError: Error, LocalizedError, Equatable {
    case accessibilityPermissionDenied
    case inputMonitoringPermissionDenied
    case eventTapUnavailable
    case alreadyActive
    case invalidExpiry

    public var errorDescription: String? {
        switch self {
        case .accessibilityPermissionDenied:
            return "Accessibility permission is required to suppress physical keyboard events"
        case .inputMonitoringPermissionDenied:
            return "Input Monitoring permission is required to suppress physical keyboard events"
        case .eventTapUnavailable:
            return "macOS could not install the physical keyboard suppression event tap"
        case .alreadyActive:
            return "Physical keyboard suppression is already active"
        case .invalidExpiry:
            return "Physical keyboard suppression requires a future expiry time"
        }
    }
}

public protocol PhysicalKeyboardSuppressing {
    func acquire(until: Date) throws
    func release()
}

enum MacCtlKeyboardEventMetadata {
    // "MACCTLKB" in hexadecimal. This marks only events generated by this
    // control plane so an opt-in physical-keyboard lock does not block them.
    static let syntheticUserData: Int64 = 0x4D414343544C4B42

    static func markSynthetic(_ event: CGEvent) {
        event.setIntegerValueField(.eventSourceUserData, value: syntheticUserData)
    }

    static func isSynthetic(_ event: CGEvent) -> Bool {
        event.getIntegerValueField(.eventSourceUserData) == syntheticUserData
    }
}

/// Suppresses physical keyboard events in the current macOS user session.
///
/// This is intentionally a session event tap rather than a device or driver
/// lock. It is bounded by the lease lifetime, releases on explicit cleanup,
/// and disappears with the daemon process. Mouse input remains available so
/// the user can use the status-item quit action as an emergency release path.
public final class SystemPhysicalKeyboardSuppressor: PhysicalKeyboardSuppressing {
    private let stateLock = NSLock()
    private var eventTap: CFMachPort?
    private var runLoopSource: CFRunLoopSource?
    private var activeUntil: Date?

    public init() {}

    deinit {
        release()
    }

    public func acquire(until: Date) throws {
        guard until > Date() else {
            throw PhysicalKeyboardSuppressionError.invalidExpiry
        }
        guard PermissionDiagnostics.hasAccessibility() else {
            throw PhysicalKeyboardSuppressionError.accessibilityPermissionDenied
        }
        guard PermissionDiagnostics.hasListenEventAccess() else {
            throw PhysicalKeyboardSuppressionError.inputMonitoringPermissionDenied
        }

        try onMain { [self] in
            try startOnMain(until: until)
        }
    }

    public func release() {
        try? onMain { [self] in
            stopOnMain()
        }
    }

    private func startOnMain(until: Date) throws {
        precondition(Thread.isMainThread)
        stateLock.lock()
        let alreadyActive = eventTap != nil
        stateLock.unlock()
        guard !alreadyActive else {
            throw PhysicalKeyboardSuppressionError.alreadyActive
        }

        let mask = Self.keyboardEventMask
        guard let tap = CGEvent.tapCreate(
            tap: .cgSessionEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: mask,
            callback: SystemPhysicalKeyboardSuppressor.eventCallback,
            userInfo: Unmanaged.passUnretained(self).toOpaque()
        ) else {
            throw PhysicalKeyboardSuppressionError.eventTapUnavailable
        }
        guard let source = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0) else {
            CFMachPortInvalidate(tap)
            throw PhysicalKeyboardSuppressionError.eventTapUnavailable
        }

        stateLock.lock()
        eventTap = tap
        runLoopSource = source
        activeUntil = until
        stateLock.unlock()

        CFRunLoopAddSource(CFRunLoopGetMain(), source, .commonModes)
        CGEvent.tapEnable(tap: tap, enable: true)
    }

    private func stopOnMain() {
        precondition(Thread.isMainThread)
        stateLock.lock()
        let source = runLoopSource
        let tap = eventTap
        runLoopSource = nil
        eventTap = nil
        activeUntil = nil
        stateLock.unlock()

        if let source {
            CFRunLoopRemoveSource(CFRunLoopGetMain(), source, .commonModes)
        }
        if let tap {
            CGEvent.tapEnable(tap: tap, enable: false)
            CFMachPortInvalidate(tap)
        }
    }

    private func shouldSuppress(_ event: CGEvent) -> Bool {
        if MacCtlKeyboardEventMetadata.isSynthetic(event) {
            return false
        }
        stateLock.lock()
        let until = activeUntil
        stateLock.unlock()
        return until.map { $0 > Date() } ?? false
    }

    private func reenableEventTap() {
        stateLock.lock()
        let tap = eventTap
        stateLock.unlock()
        if let tap {
            CGEvent.tapEnable(tap: tap, enable: true)
        }
    }

    private static let keyboardEventMask: CGEventMask = {
        CGEventMask(1 << CGEventType.keyDown.rawValue)
            | CGEventMask(1 << CGEventType.keyUp.rawValue)
            | CGEventMask(1 << CGEventType.flagsChanged.rawValue)
    }()

    private static let eventCallback: CGEventTapCallBack = { _, type, event, refcon in
        guard let refcon else { return Unmanaged.passUnretained(event) }
        let suppressor = Unmanaged<SystemPhysicalKeyboardSuppressor>
            .fromOpaque(refcon)
            .takeUnretainedValue()
        switch type {
        case .tapDisabledByTimeout, .tapDisabledByUserInput:
            suppressor.reenableEventTap()
            return Unmanaged.passUnretained(event)
        default:
            return suppressor.shouldSuppress(event)
                ? nil
                : Unmanaged.passUnretained(event)
        }
    }

    private func onMain<T>(_ work: @escaping () throws -> T) throws -> T {
        if Thread.isMainThread {
            return try work()
        }
        var result: Result<T, Error>!
        DispatchQueue.main.sync {
            result = Result { try work() }
        }
        return try result.get()
    }
}
